//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WocketsApplication.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WocketsApplication.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap AddPressed {
            get {
                object obj = ResourceManager.GetObject("AddPressed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap AddUnpressed {
            get {
                object obj = ResourceManager.GetObject("AddUnpressed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap AnnotatePressed {
            get {
                object obj = ResourceManager.GetObject("AnnotatePressed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap AnnotateUnpressed {
            get {
                object obj = ResourceManager.GetObject("AnnotateUnpressed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Back32Pressed {
            get {
                object obj = ResourceManager.GetObject("Back32Pressed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Back32Unpressed {
            get {
                object obj = ResourceManager.GetObject("Back32Unpressed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Back64Pressed {
            get {
                object obj = ResourceManager.GetObject("Back64Pressed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Back64Unpressed {
            get {
                object obj = ResourceManager.GetObject("Back64Unpressed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BackPressed {
            get {
                object obj = ResourceManager.GetObject("BackPressed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BackUnpressed {
            get {
                object obj = ResourceManager.GetObject("BackUnpressed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BatteryPressed {
            get {
                object obj = ResourceManager.GetObject("BatteryPressed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BatteryUnpressed {
            get {
                object obj = ResourceManager.GetObject("BatteryUnpressed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BluetoothPressed {
            get {
                object obj = ResourceManager.GetObject("BluetoothPressed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BluetoothPressed_48 {
            get {
                object obj = ResourceManager.GetObject("BluetoothPressed_48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BluetoothUnpressed {
            get {
                object obj = ResourceManager.GetObject("BluetoothUnpressed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BluetoothUnpressed_48 {
            get {
                object obj = ResourceManager.GetObject("BluetoothUnpressed_48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap CommandPressed {
            get {
                object obj = ResourceManager.GetObject("CommandPressed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap CommandPressed_48 {
            get {
                object obj = ResourceManager.GetObject("CommandPressed_48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap CommandUnpressed {
            get {
                object obj = ResourceManager.GetObject("CommandUnpressed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap CommandUnpressed_48 {
            get {
                object obj = ResourceManager.GetObject("CommandUnpressed_48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap CoolBlue {
            get {
                object obj = ResourceManager.GetObject("CoolBlue", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap CosmosRed {
            get {
                object obj = ResourceManager.GetObject("CosmosRed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DottedBlack {
            get {
                object obj = ResourceManager.GetObject("DottedBlack", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static byte[] DottedBlack1 {
            get {
                object obj = ResourceManager.GetObject("DottedBlack1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Down64Pressed {
            get {
                object obj = ResourceManager.GetObject("Down64Pressed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Down64Unpressed {
            get {
                object obj = ResourceManager.GetObject("Down64Unpressed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap GraphiteBlue {
            get {
                object obj = ResourceManager.GetObject("GraphiteBlue", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap HeartPressed {
            get {
                object obj = ResourceManager.GetObject("HeartPressed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap HeartUnpressed {
            get {
                object obj = ResourceManager.GetObject("HeartUnpressed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap InformationPressed_48 {
            get {
                object obj = ResourceManager.GetObject("InformationPressed_48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap InformationUnpressed_48 {
            get {
                object obj = ResourceManager.GetObject("InformationUnpressed_48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Leather {
            get {
                object obj = ResourceManager.GetObject("Leather", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap LineChartPressed {
            get {
                object obj = ResourceManager.GetObject("LineChartPressed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap LineChartUnpressed {
            get {
                object obj = ResourceManager.GetObject("LineChartUnpressed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap MinimizePressed {
            get {
                object obj = ResourceManager.GetObject("MinimizePressed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap MinimizeUnpressed {
            get {
                object obj = ResourceManager.GetObject("MinimizeUnpressed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap NaturalBlack {
            get {
                object obj = ResourceManager.GetObject("NaturalBlack", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap RemovePressed {
            get {
                object obj = ResourceManager.GetObject("RemovePressed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap RemoveUnpressed {
            get {
                object obj = ResourceManager.GetObject("RemoveUnpressed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SettingsPressed {
            get {
                object obj = ResourceManager.GetObject("SettingsPressed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SettingsUnpressed {
            get {
                object obj = ResourceManager.GetObject("SettingsUnpressed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SignalQualityPressed {
            get {
                object obj = ResourceManager.GetObject("SignalQualityPressed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SignalQualityUnpressed {
            get {
                object obj = ResourceManager.GetObject("SignalQualityUnpressed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SoundPressed {
            get {
                object obj = ResourceManager.GetObject("SoundPressed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SoundUnpressed {
            get {
                object obj = ResourceManager.GetObject("SoundUnpressed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SpiderBlack {
            get {
                object obj = ResourceManager.GetObject("SpiderBlack", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap StatisticsPressed {
            get {
                object obj = ResourceManager.GetObject("StatisticsPressed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap StatisticsUnpressed {
            get {
                object obj = ResourceManager.GetObject("StatisticsUnpressed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap StatusPressed_48 {
            get {
                object obj = ResourceManager.GetObject("StatusPressed_48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap StatusUnpressed_48 {
            get {
                object obj = ResourceManager.GetObject("StatusUnpressed_48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap TimerPressed_48 {
            get {
                object obj = ResourceManager.GetObject("TimerPressed_48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap TimerUnpressed_48 {
            get {
                object obj = ResourceManager.GetObject("TimerUnpressed_48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap TurnOffPressed {
            get {
                object obj = ResourceManager.GetObject("TurnOffPressed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap TurnOffUnpressed {
            get {
                object obj = ResourceManager.GetObject("TurnOffUnpressed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Up64Pressed {
            get {
                object obj = ResourceManager.GetObject("Up64Pressed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Up64Unpressed {
            get {
                object obj = ResourceManager.GetObject("Up64Unpressed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
