/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface;

import bluetooth.CalibrationValues;
import bluetooth.PcClient;
import java.awt.CardLayout;
import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.microedition.io.StreamConnection;
import javax.swing.JPanel;
import javax.swing.SwingUtilities;
import org.xmlpull.v1.XmlPullParserException;
import wocketXML.XMLWriter;

/**
 *
 * @author Aida
 */
public class BatteryTest extends javax.swing.JPanel {

    JPanel userProcessContainer;
    InputStream inStream = null;
    OutputStream outStream = null;
    CalibrationValues calibrationValues;
    
    public BatteryTest(JPanel upc, InputStream is, OutputStream os, CalibrationValues cv) throws IOException {
        initComponents();
        userProcessContainer = upc;userProcessContainer = upc;
        outStream = os;
        inStream = is;
        calibrationValues = cv;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        startButton = new javax.swing.JButton();
        backButton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        messageLabel1 = new javax.swing.JLabel();
        skipButton = new javax.swing.JButton();

        startButton.setText("Start ");
        startButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startButtonActionPerformed(evt);
            }
        });

        backButton.setText("Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        jLabel4.setText("Leave all Wockets on the table next to the bluetooth adaptor.");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Battery life testing");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("PC-Wocket Application");

        jLabel5.setText("When you are ready, click \"Start\".");

        messageLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        messageLabel1.setText(" ");

        skipButton.setText("Skip Battery Test");
        skipButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                skipButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(backButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(skipButton)
                        .addGap(82, 82, 82)
                        .addComponent(startButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(messageLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(57, 57, 57)
                                    .addComponent(jLabel1))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(89, 89, 89)
                                    .addComponent(jLabel3))
                                .addComponent(jLabel4)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(61, 61, 61)
                                    .addComponent(jLabel5))))
                        .addGap(0, 36, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addGap(31, 31, 31)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addGap(48, 48, 48)
                .addComponent(messageLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 140, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(backButton)
                    .addComponent(startButton)
                    .addComponent(skipButton)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void startButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startButtonActionPerformed
        startButton.setVisible(false);
        SwingUtilities.invokeLater(testBatteryRunnable);
        messageLabel1.setText("Testing the Battery life... It may take 6-8 hours.");               
    }//GEN-LAST:event_startButtonActionPerformed

    Runnable testBatteryRunnable = new Runnable() {
        public void run() { 
            try {
                int[] btCal = PcClient.testBattery(outStream, inStream);
                calibrationValues.setBattery_calibration(btCal);
                PcClient.beepRunnable.run();
                JPanel btSummaryPanel = new BatteryLifeSummary(userProcessContainer, inStream, outStream, calibrationValues);
                userProcessContainer.add("btSummaryPanel",btSummaryPanel);
                CardLayout c1 = (CardLayout)userProcessContainer.getLayout();
                c1.next(userProcessContainer);
            } catch (IOException ex) {
                Logger.getLogger(BatteryTest.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    };
        
    
    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        userProcessContainer.remove(this);
        CardLayout c1 = (CardLayout)userProcessContainer.getLayout();
        c1.previous(userProcessContainer);
    }//GEN-LAST:event_backButtonActionPerformed

    private void skipButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_skipButtonActionPerformed
        try {
            XMLWriter.write(calibrationValues);
        } catch (XmlPullParserException ex) {
            System.out.println("XmlPullParserException in Test Battery jPanel");
        } catch (IOException ex) {
            Logger.getLogger(BatteryTest.class.getName()).log(Level.SEVERE, null, ex);
        }
        JPanel donePanel= null;
        try {
            donePanel = new DoneCalibration(userProcessContainer, inStream, outStream);
        } catch (IOException ex) {
            Logger.getLogger(BatteryLifeSummary.class.getName()).log(Level.SEVERE, null, ex);
        }
        userProcessContainer.add("donePanel",donePanel);
        CardLayout c1 = (CardLayout)userProcessContainer.getLayout();
        c1.next(userProcessContainer);
    }//GEN-LAST:event_skipButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel messageLabel1;
    private javax.swing.JButton skipButton;
    private javax.swing.JButton startButton;
    // End of variables declaration//GEN-END:variables
}
